# Cloud Build configuration for deploying AI Data Cleaning Assistant to Cloud Run
# 
# Note: Services are deployed with --allow-unauthenticated flag to enable public access.
# Explicit IAM policy binding steps follow each deployment to ensure public access is granted.
# This prevents 403 Forbidden errors that can occur when the Cloud Build service account
# lacks the setIamPolicy permission during the initial deployment.

substitutions:
  _REGION: asia-southeast2
  _REPO: ai-data-cleaning-repo
  _API_SERVICE: ai-data-cleaning-api
  _MCP_SERVICE: ai-data-cleaning-mcp
  _N8N_SERVICE: ai-data-cleaning-n8n

steps:
  # --------------------
  # Build API image
  # --------------------
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api:${BUILD_ID}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api:${BUILD_ID}

  # --------------------
  # Build MCP image
  # --------------------
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - mcp/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/mcp:${BUILD_ID}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/mcp:${BUILD_ID}

  # --------------------
  # Deploy API
  # --------------------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_API_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api:${BUILD_ID}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - GCS_BUCKET=ai-data-cleaning-data

  # Explicitly grant public access to API service
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - add-iam-policy-binding
      - ${_API_SERVICE}
      - --region=${_REGION}
      - --member=allUsers
      - --role=roles/run.invoker

  # --------------------
  # Deploy MCP
  # --------------------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_MCP_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/mcp:${BUILD_ID}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated

  # Explicitly grant public access to MCP service
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - add-iam-policy-binding
      - ${_MCP_SERVICE}
      - --region=${_REGION}
      - --member=allUsers
      - --role=roles/run.invoker

  # --------------------
  # Deploy n8n
  # --------------------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_N8N_SERVICE}
      - --image
      - n8nio/n8n
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - '5678'
      - --set-env-vars
      - N8N_BASIC_AUTH_ACTIVE=true,N8N_BASIC_AUTH_USER=admin,N8N_BASIC_AUTH_PASSWORD=admin

  # Explicitly grant public access to n8n service
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - add-iam-policy-binding
      - ${_N8N_SERVICE}
      - --region=${_REGION}
      - --member=allUsers
      - --role=roles/run.invoker
